definitions:
  scripts:
    - &build_framework
      name: Build framework
      script: xcodebuild -scheme $XCODE_SCHEME -destination 'platform=iOS Simulator,name=iPhone 13'
    - &test_framework
      name: Test framework
      script: xcodebuild -scheme $XCODE_SCHEME -destination 'platform=iOS Simulator,name=iPhone 13' test | xcpretty --report junit
      test_report: build/reports/junit.xml

workflows:
  musadorakit-workflow:
    name: MusadoraKit Workflow
    instance_type: mac_mini_m1
    environment:
      xcode: 14.0
      vars:
        XCODE_SCHEME: MusadoraKit
    triggering:
      events:
        - push
    when:
      changeset:
        includes:
          - "Sources/MusadoraKit/"
          - "Tests/MusadoraKitTests/"
    scripts:
      - *build_framework
      - *test_framework
  musadorlabskit-workflow:
    name: MusadoraLabsKit Workflow
    instance_type: mac_mini_m1
    environment:
      xcode: 14.0
      vars:
        XCODE_SCHEME: MusadoraLabsKit
    triggering:
      events:
        - push
    when:
      changeset:
        includes:
          - "Sources/MusadoraLabsKit/"
          - "Tests/MusadoraLabsKitTests/"
    scripts:
      - *build_framework
      - *test_framework
