workflows:
  musadorakit-workflow:
    name: MusadoraKit Workflow
    instance_type: mac_mini
    environment:
      xcode: latest
    triggering:
      events:
        - push
    when:
      changeset:
        includes:
          - "Sources/MusadoraKit/"
          - "Tests/MusadoraLabsKit/"
    scripts:
      - name: Build MusadoraKit
        script: xcodebuild -scheme MusadoraKit -destination 'platform=iOS Simulator,name=iPhone 12'
      - name: Test
        script: xcodebuild -scheme MusadoraKit -destination 'platform=iOS Simulator,name=iPhone 12' test | xcpretty
        test_report: build/ios/test/*.xml
  musadorlabskit-workflow:
    name: MusadoraLabsKit Workflow
    instance_type: mac_mini
    environment:
      xcode: latest
    triggering:
      events:
        - push
    when:
      changeset:
        includes:
          - "Sources/MusadoraLabsKit/"
          - "Tests/MusadoraLabsKit/"
    scripts:
      - name: Build MusadoraLabsKit
        script: xcodebuild -scheme MusadoraLabsKit -destination 'platform=iOS Simulator,name=iPhone 12'
      - name: Test
        script: xcodebuild -scheme MusadoraLabsKit -destination 'platform=iOS Simulator,name=iPhone 12' test | xcpretty
        test_report: build/ios/test/*.xml
