definitions:
  triggering:
    push: &events
      events:
        - push
        - pull_request
    scripts:
      - &buildFramework
        name: Build Framework
        script: sh build.sh
        when:
          changeset:
            includes:
              - 'Sources'
              - 'Tests'
      - &testFramework
        name: Test Framework
        script: |
          set -o pipefail
          sh test.sh
        when:
          changeset:
            includes:
              - 'Sources'
              - 'Tests'
        test_report: build/reports/junit.xml
      - &buildMusadoraApp
        name: Build Musadora App
        working_directory: Musadora
        script: |
          xcodebuild clean build \
           -project Musadora.xcodeproj \
           -scheme Musadora \
           -destination "platform=iOS Simulator,name=iPhone 14" \
           -skipPackagePluginValidation
        when:
          changeset:
            includes:
              - 'Musadora'
      - &updateDocs
        name: Update DocC Documentation
        script: |
          sh build_docs.sh
          git add .
          git commit -m "[skip ci] Update DocC Documentation"
          git remote set-url origin https://rudrankriyam:$token@github.com/rryam/MusadoraKit.git
          git pull --ff-only
          git push origin main

workflows:
  musadorakit:
    name: MusadoraKit Workflow
    instance_type: mac_mini_m1
    environment:
      groups:
        - GitHub
    triggering:
      <<: *events
    scripts:
      - *buildFramework
      - *testFramework
      - *buildMusadoraApp
  musadorakit-update-docs:
    name: MusadoraKit Docs Update Workflow
    environment:
      groups:
        - GitHub
    scripts:
      - *updateDocs
