definitions:
  triggering:
    push: &events
      events:
        - push
        - pull_request
    scripts:
      - &buildFramework
        name: Build Framework
        script: sh build.sh
      - &testFramework
        name: Test Framework
        script: |
          set -o pipefail
          sh test.sh
        test_report: build/reports/junit.xml
      - &buildMusadoraApp
        name: Build Musadora App
        working_directory: Musadora
        script: |
          xcodebuild clean build \
           -project Musadora.xcodeproj \
           -scheme Musadora \
           -destination "platform=iOS Simulator,name=iPhone 14" \
           -skipPackagePluginValidation
      - &updateDocs
        name: Update DocC Documentation
        script: |
          git remote set-url origin https://rudrankriyam:$token@github.com/rryam/MusadoraKit.git
          git merge our-team
          sh build_docs.sh
          git add .
          git commit -m "[skip ci] Update DocC Documentation"
          git pull --ff-only
          git push origin docs

workflows:
  musadorakit:
    name: MusadoraKit Workflow
    instance_type: mac_mini_m1
    environment:
      xcode: 14.2
      groups:
        - GitHub
    when:
      changeset:
        includes:
          - 'Sources'
          - 'Tests'
    triggering:
      <<: *events
    scripts:
      - *buildFramework
      - *testFramework
      - *updateDocs
  musadora:
    name: Musadora Workflow
    instance_type: mac_mini_m1
    environment:
      xcode: 14.2
      groups:
        - GitHub
    when:
      changeset:
        includes:
          - 'Musadora'
          - 'Tests'
    triggering:
      <<: *events
    scripts:
      - *buildMusadoraApp
