definitions:
  triggering:
    push: &events
      events:
        - push
        - pull_request
        - tag
    scripts:
      - &buildFramework
        name: Build Framework
        script: xcodebuild -scheme $XCODE_SCHEME -destination "platform=iOS Simulator,name=$PHONE_NAME"
      - &testFramework
        name: Test Framework
        script: |
          set -o pipefail
          xcodebuild -scheme $XCODE_SCHEME -destination "platform=iOS Simulator,name=$PHONE_NAME" test | xcpretty --report junit
        test_report: build/reports/junit.xml
      - &updateDocs
        name: Update DocC Documentation
        script: | 
          sh build_docs.sh 
          git add .
          git commit -m "[skip ci] Update DocC Documentation"
          git remote set-url origin https://rudrankriyam:$token@github.com/rryam/MusadoraKit.git
          git pull --ff-only
          git push origin main

workflows:
  musadorakit:
    name: MusadoraKit Workflow
    environment:
      xcode: 14.2
      groups: 
        - GitHub
      vars:
        XCODE_SCHEME: MusadoraKit
        PHONE_NAME: "iPhone 14"
    triggering:
      <<: *events
    scripts: 
      - *buildFramework
      - *testFramework
      - *updateDocs
  musadorakit-old:
    name: MusadoraKit Xcode 13 Workflow
    environment:
      xcode: 13.4.1
      groups: 
        - GitHub
      vars:
        XCODE_SCHEME: MusadoraKit
        PHONE_NAME: "iPhone 13"
    triggering:
      <<: *events
    scripts: 
      - *buildFramework
      - *testFramework
