definitions:
  triggering:
    push: &events
      events:
        - push
        - pull_request
    scripts:
      - &buildFramework
        name: Build Framework
        script: |
          xcodebuild \
            -scheme $XCODE_SCHEME \
            -destination "$DESTINATION" \
            -skipPackagePluginValidation \
            clean build
      - &testFramework
        name: Test Framework
        script: |
          set -o pipefail
          xcodebuild \
            -scheme $XCODE_SCHEME \
            -destination "$DESTINATION" \
            -skipPackagePluginValidation \
            test | xcpretty --report junit
        test_report: build/reports/junit.xml
      - &updateDocs
        name: Update DocC Documentation
        script: | 
          sh build_docs.sh 
          git add .
          git commit -m "[skip ci] Update DocC Documentation"
          git remote set-url origin https://rudrankriyam:$token@github.com/rryam/MusadoraKit.git
          git pull --ff-only
          git push origin main

workflows:
  musadorakit:
    name: MusadoraKit Workflow
    instance_type: mac_mini_m1
    environment:
      xcode: 14.2
      groups: 
        - GitHub
      vars:
        XCODE_SCHEME: MusadoraKit
        DESTINATION: "platform=iOS Simulator,name=iPhone 14"
    triggering:
      <<: *events
    scripts: 
      - *buildFramework
      - *testFramework
      - *updateDocs
