definitions:
  env_versions: &env_versions
    xcode: latest
  triggering:
    push: &push_event
      events:
        - push
  scripts:
    - &build
      name: Build MusadoraKit
      script: xcodebuild -scheme $SCHEME -destination 'platform=iOS Simulator,name=iPhone 12'
    - &test
      name: Test
      script: xcodebuild -scheme $SCHEME -destination 'platform=iOS Simulator,name=iPhone 12' test | xcpretty --report junit
      test_report: build/reports/junit.xml

workflows:
  musadorakit-workflow:
    name: MusadoraKit Workflow
    instance_type: mac_pro
    environment:
      <<: *env_versions
      vars:
        SCHEME: "MusadoraKit"
    triggering:
      <<: *push_event
    when:
      changeset:
        includes:
          - "Sources/MusadoraKit/"
          - "Tests/MusadoraLabsKit/"
    scripts:
      - *build
      - *test
  musadorlabskit-workflow:
    name: MusadoraLabsKit Workflow
    instance_type: mac_pro
    environment:
      <<: *env_versions
      vars:
        SCHEME: "MusadoraLabsKit"
    triggering:
      <<: *push_event
    when:
      changeset:
        includes:
          - "Sources/MusadoraLabsKit/"
          - "Tests/MusadoraLabsKit/"
    scripts:
      - *build
      - *test
